services:
  api:
    env_file:
      - .env.production
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "npm run build && npm run seed:prod && npm run start:prod"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./src:/app/api/src
    ports:
      - "8000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    links:
      - postgres
      - minio
    networks:
      - energet-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/postgres/docker-volumes/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - energet-network

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://minio:9000/minio/health/live; }
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid
        until isAlive; do sleep 1; done
        echo "MinIO is ready. Proceeding with setup..."
        mc alias set myminio http://minio:9000 minio minio123
        mc mb myminio/images/ --ignore-existing
        mc anonymous set public myminio/images
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $$0 "$$@"
        '
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - minio-data:/data
    networks:
      - energet-network

  telegram-notifier:
    image: lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TELEGRAM_NOTIFIER_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_NOTIFIER_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_NOTIFIER_TOPIC_ID: ${TELEGRAM_TOPIC_ID}
    labels:
      telegram-notifier.monitor: false

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - './infra/grafana/dashboards:/etc/grafana/provisioning/dashboards'
      - './infra/grafana/datasources:/etc/grafana/provisioning/datasources'
      - './infra/grafana/config:/etc/grafana-config'
      - './infra/grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - grafana-storage:/var/lib/grafana
    networks:
      - energet-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - energet-network

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "8027:8027"
    entrypoint:
      - '/bin/alloy'
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--config.extra-args="-config.expand-env"'
      - '/etc/alloy/config.alloy'
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy
    networks:
      - energet-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      alloy:
        condition: service_started
      api:
        condition: service_started
    networks:
      - energet-network

volumes:
  postgres:
  pgadmin:
  minio-data:

networks:
  energet-network:
    name: energet-network
    driver: bridge
